name: build

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build:
    name: Build exercises
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: cache-conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yaml') }}

    - name: install miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,bioconda,defaults
        channel-priority: true
        environment-file: environment.yaml
        use-only-tar-bz2: true

    - name: Install python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install pgip and bash jupyter kernels
      run: |
        python -m bash_kernel.install
        python -m ipykernel install --user --name pgip --display-name "Population Genomics in Practice (Python)"

    # Build the book
    - name: Build the book
      run: ./build.sh

    - name: Copy exercises data
      run: |
        cp ./requirements.txt ./_build/html/.
        cp -r data ./_build/html/data
        ls data > ./_build/html/data/files.txt

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
